// 手机尺寸截图：开局后各页签、名录人物卡、斗法
const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path');
const {pickBody,sse}=require('./mock');
const ROOT=path.join(__dirname,'..');
const MIME={'.html':'text/html; charset=utf-8','.webp':'image/webp','.png':'image/png'};
const srv=http.createServer((q,r)=>{ let p=decodeURIComponent(q.url.split('?')[0]); if(p==='/') p='/index.html'; const f=path.join(ROOT,p); if(!fs.existsSync(f)){r.writeHead(404);r.end();return;} r.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'application/octet-stream'}); r.end(fs.readFileSync(f)); });
const OUT=process.env.SHOT_DIR||'/tmp/shots';
(async()=>{
srv.listen(8952);
const br=await chromium.launch({executablePath:process.env.PW_CHROME});
const ctx=await br.newContext({viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true});
const page=await ctx.newPage();
const errs=[]; page.on('pageerror',e=>errs.push(String(e)));
await page.route('**/chat/completions',async route=>{ const b=JSON.parse(route.request().postData()); await route.fulfill({status:200,headers:{'Content-Type':'text/event-stream'},body:sse(pickBody(b.messages[b.messages.length-1].content))}); });
await page.addInitScript(()=>{localStorage.setItem('yxxy2_cfg',JSON.stringify({base:'https://api.deepseek.com',key:'sk-test',model:'m',think:false}));});
await page.goto('http://localhost:8952/');
await page.waitForTimeout(300);
await page.screenshot({path:OUT+'/m_create.png',fullPage:true});
await page.click('#colGrid .bgopt[data-k="danxia"]');
await page.click('#crStart');
await page.waitForSelector('#choices .opt',{timeout:15000});
await page.waitForFunction(()=>!busy);
await page.screenshot({path:OUT+'/m_event.png'});
await page.click('#choices .opt >> nth=0');
await page.waitForFunction(()=>!busy&&S.turn>=2,null,{timeout:15000});
await page.waitForTimeout(400);
await page.screenshot({path:OUT+'/m_result.png'});
await page.waitForTimeout(400);
await page.screenshot({path:OUT+'/m_story.png'});
await page.click('#panelToggle'); await page.waitForTimeout(500);
await page.screenshot({path:OUT+'/m_panel.png'});
await page.click('#tabs button[data-tab="people"]'); await page.waitForTimeout(600);
await page.screenshot({path:OUT+'/m_people.png'});
await page.evaluate(()=>showNpc(findNpc('钟离衡'))); await page.waitForTimeout(400);
await page.screenshot({path:OUT+'/m_npc.png'});
await page.evaluate(()=>$('npcMask').classList.remove('on'));
await page.click('#tabs button[data-tab="world"]'); await page.waitForTimeout(400);
await page.screenshot({path:OUT+'/m_world.png'});
await page.evaluate(()=>{ setDrawer(false); startDuel(findNpc('温酒酒')||findNpc('周小满'),{friendly:true,reason:'演武场切磋',action:'切磋'}); });
await page.waitForTimeout(500);
await page.screenshot({path:OUT+'/m_duel.png'});
console.log('errors:',errs);
await br.close(); srv.close();
})();
